application: tabzhub
version: 1
runtime: python27
api_version: 1
threadsafe: True

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: views.application

libraries:
- name: jinja2
  version: "2.6"
- name: webapp2
  version: "2.5.2"
